// Package storage is where catalog-service keeps e-library files. Two
// backends behind one interface:
//
//   - s3: an object store speaking the S3 protocol — self-hosted SeaweedFS
//     in Compose and Kubernetes (no cloud account). Every catalog replica
//     sees the same files, which is what lets catalog scale past one pod (a local
//     ReadWriteOnce volume pinned it to one).
//   - local: a directory, for running catalog with bare `go run`.
package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

// ErrNotFound: no object under that key.
var ErrNotFound = errors.New("object not found")

// Object is an open stored file. ReadSeeker so http.ServeContent can
// answer range requests (resumable downloads, epub.js fetching parts).
type Object interface {
	io.ReadSeeker
	io.Closer
}

type Store interface {
	// Put stores size bytes from r under key, replacing any existing object.
	Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error
	// Open returns the object and its modification time.
	Open(ctx context.Context, key string) (Object, time.Time, error)
	Delete(ctx context.Context, key string) error
	Ping(ctx context.Context) error
}

// ── Local directory ─────────────────────────────────────────────────────

type localStore struct {
	root string
}

func NewLocal(root string) (Store, error) {
	if err := os.MkdirAll(root, 0o750); err != nil {
		return nil, err
	}
	return &localStore{root: root}, nil
}

// path confines key to the root — keys are generated by catalog, but a
// store must never be talked into writing outside its directory.
func (s *localStore) path(key string) (string, error) {
	p := filepath.Join(s.root, filepath.FromSlash(key))
	if !strings.HasPrefix(p, filepath.Clean(s.root)+string(os.PathSeparator)) {
		return "", fmt.Errorf("storage key %q escapes the store root", key)
	}
	return p, nil
}

func (s *localStore) Put(_ context.Context, key string, r io.Reader, _ int64, _ string) error {
	p, err := s.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		return err
	}
	// Write to a temp file and rename: readers never see a half-written file.
	tmp, err := os.CreateTemp(filepath.Dir(p), ".upload-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := io.Copy(tmp, r); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), p)
}

func (s *localStore) Open(_ context.Context, key string) (Object, time.Time, error) {
	p, err := s.path(key)
	if err != nil {
		return nil, time.Time{}, err
	}
	f, err := os.Open(p) // #nosec G304 -- p is confined to the store root by s.path
	if errors.Is(err, os.ErrNotExist) {
		return nil, time.Time{}, ErrNotFound
	}
	if err != nil {
		return nil, time.Time{}, err
	}
	info, err := f.Stat()
	if err != nil {
		f.Close()
		return nil, time.Time{}, err
	}
	return f, info.ModTime(), nil
}

func (s *localStore) Delete(_ context.Context, key string) error {
	p, err := s.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func (s *localStore) Ping(context.Context) error {
	_, err := os.Stat(s.root)
	return err
}

// ── S3-compatible object storage ────────────────────────────────────────

type s3Store struct {
	client *minio.Client
	bucket string
}

type S3Config struct {
	Endpoint  string // host:port, no scheme
	AccessKey string
	SecretKey string
	Bucket    string
	UseSSL    bool
	Region    string
}

// NewS3 connects and creates the bucket if it doesn't exist (retrying
// while the object store starts).
func NewS3(ctx context.Context, cfg S3Config) (Store, error) {
	client, err := minio.New(cfg.Endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(cfg.AccessKey, cfg.SecretKey, ""),
		Secure: cfg.UseSSL,
		Region: cfg.Region,
	})
	if err != nil {
		return nil, err
	}

	var lastErr error
	for attempt := 1; attempt <= 15; attempt++ {
		exists, err := client.BucketExists(ctx, cfg.Bucket)
		if err == nil && !exists {
			err = client.MakeBucket(ctx, cfg.Bucket, minio.MakeBucketOptions{Region: cfg.Region})
		}
		if err == nil {
			return &s3Store{client: client, bucket: cfg.Bucket}, nil
		}
		lastErr = err
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(2 * time.Second):
		}
	}
	return nil, fmt.Errorf("object storage not reachable: %w", lastErr)
}

func (s *s3Store) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	_, err := s.client.PutObject(ctx, s.bucket, key, r, size, minio.PutObjectOptions{ContentType: contentType})
	return err
}

func (s *s3Store) Open(ctx context.Context, key string) (Object, time.Time, error) {
	info, err := s.client.StatObject(ctx, s.bucket, key, minio.StatObjectOptions{})
	if err != nil {
		if minio.ToErrorResponse(err).Code == "NoSuchKey" {
			return nil, time.Time{}, ErrNotFound
		}
		return nil, time.Time{}, err
	}
	obj, err := s.client.GetObject(ctx, s.bucket, key, minio.GetObjectOptions{})
	if err != nil {
		return nil, time.Time{}, err
	}
	return obj, info.LastModified, nil
}

func (s *s3Store) Delete(ctx context.Context, key string) error {
	return s.client.RemoveObject(ctx, s.bucket, key, minio.RemoveObjectOptions{})
}

func (s *s3Store) Ping(ctx context.Context) error {
	_, err := s.client.BucketExists(ctx, s.bucket)
	return err
}
