FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY conf.d/default.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget -qO- http://localhost:80/ || exit 1
