package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	borrowv1 "github.com/dprince-03/Bibliomania/gen/borrow/v1"
	catalogv1 "github.com/dprince-03/Bibliomania/gen/catalog/v1"
	readingv1 "github.com/dprince-03/Bibliomania/gen/reading/v1"
	userv1 "github.com/dprince-03/Bibliomania/gen/user/v1"
	"github.com/dprince-03/Bibliomania/internal/gateway/graph/model"
	"github.com/dprince-03/Bibliomania/internal/grpcx"
	"github.com/dprince-03/Bibliomania/internal/middleware"
)

// MyBorrowStatus is the resolver for the myBorrowStatus field.
func (r *bookResolver) MyBorrowStatus(ctx context.Context, obj *model.Book) (*model.BorrowRecord, error) {
	if middleware.GetUserID(ctx) == 0 {
		return nil, nil
	}
	bookID, err := parseID(obj.ID, "book id")
	if err != nil {
		return nil, err
	}
	rec, err := r.Borrow.GetMyActiveBorrow(ctx, &borrowv1.GetMyActiveBorrowRequest{BookId: bookID})
	if err != nil {
		if err := grpcx.FromStatus(err); isNotFound(err) {
			return nil, nil
		} else {
			return nil, err
		}
	}
	return borrowFromProto(rec), nil
}

// MyLibraryStatus is the resolver for the myLibraryStatus field.
func (r *bookResolver) MyLibraryStatus(ctx context.Context, obj *model.Book) (*model.LibraryStatus, error) {
	if middleware.GetUserID(ctx) == 0 {
		return nil, nil
	}
	bookID, err := parseID(obj.ID, "book id")
	if err != nil {
		return nil, err
	}
	entry, err := r.User.GetLibraryEntry(ctx, &userv1.GetLibraryEntryRequest{BookId: bookID})
	if err != nil {
		if err := grpcx.FromStatus(err); isNotFound(err) {
			return nil, nil
		} else {
			return nil, err
		}
	}
	status := model.LibraryStatus(strings.ToUpper(entry.GetStatus()))
	return &status, nil
}

// Book is the resolver for the book field.
func (r *borrowRecordResolver) Book(ctx context.Context, obj *model.BorrowRecord) (*model.Book, error) {
	return r.getBook(ctx, obj.BookID)
}

// Book is the resolver for the book field.
func (r *libraryEntryResolver) Book(ctx context.Context, obj *model.LibraryEntry) (*model.Book, error) {
	if obj.Prefetched != nil || obj.Missing {
		return obj.Prefetched, nil
	}
	return r.getBook(ctx, obj.BookID)
}

// BorrowBook is the resolver for the borrowBook field.
func (r *mutationResolver) BorrowBook(ctx context.Context, bookID string, idempotencyKey *string) (*model.BorrowRecord, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(bookID, "book id")
	if err != nil {
		return nil, err
	}
	key := ""
	if idempotencyKey != nil {
		key = *idempotencyKey
	}
	rec, err := r.Borrow.BorrowBook(ctx, &borrowv1.BorrowBookRequest{BookId: id, IdempotencyKey: key})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return borrowFromProto(rec), nil
}

// ReturnBook is the resolver for the returnBook field.
func (r *mutationResolver) ReturnBook(ctx context.Context, borrowID string) (*model.BorrowRecord, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(borrowID, "borrow id")
	if err != nil {
		return nil, err
	}
	rec, err := r.Borrow.ReturnBook(ctx, &borrowv1.ReturnBookRequest{BorrowId: id})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return borrowFromProto(rec), nil
}

// UpdateLibraryStatus is the resolver for the updateLibraryStatus field.
func (r *mutationResolver) UpdateLibraryStatus(ctx context.Context, bookID string, status model.LibraryStatus) (*model.LibraryEntry, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(bookID, "book id")
	if err != nil {
		return nil, err
	}
	entry, err := r.User.UpdateLibraryStatus(ctx, &userv1.UpdateLibraryStatusRequest{
		BookId: id,
		Status: strings.ToLower(string(status)),
	})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return libraryFromProto(entry), nil
}

// UpdateReadingProgress is the resolver for the updateReadingProgress field.
func (r *mutationResolver) UpdateReadingProgress(ctx context.Context, bookID string, currentPage int, totalPages int, currentChapter *string) (*model.ReadingHistoryEntry, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(bookID, "book id")
	if err != nil {
		return nil, err
	}
	if currentPage < 0 || totalPages < 1 {
		return nil, badInput("currentPage must be >= 0 and totalPages >= 1")
	}
	sess, err := r.Reading.UpdateProgress(ctx, &readingv1.UpdateProgressRequest{
		BookId:         id,
		CurrentPage:    uint32(currentPage),
		TotalPages:     uint32(totalPages),
		CurrentChapter: currentChapter,
	})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return historyFromProto(sess), nil
}

// CreateBookmark is the resolver for the createBookmark field.
func (r *mutationResolver) CreateBookmark(ctx context.Context, bookID string, page int, note *string, highlight *string, color *string) (*model.Bookmark, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(bookID, "book id")
	if err != nil {
		return nil, err
	}
	if page < 1 {
		return nil, badInput("page must be >= 1")
	}
	c := ""
	if color != nil {
		c = *color
	}
	b, err := r.Reading.CreateBookmark(ctx, &readingv1.CreateBookmarkRequest{
		BookId: id, Page: uint32(page), Note: note, Highlight: highlight, Color: c,
	})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return bookmarkFromProto(b), nil
}

// DeleteBookmark is the resolver for the deleteBookmark field.
func (r *mutationResolver) DeleteBookmark(ctx context.Context, bookID string, bookmarkID string) (bool, error) {
	if err := requireUser(ctx); err != nil {
		return false, err
	}
	bID, err := parseID(bookID, "book id")
	if err != nil {
		return false, err
	}
	bmID, err := parseID(bookmarkID, "bookmark id")
	if err != nil {
		return false, err
	}
	if _, err := r.Reading.DeleteBookmark(ctx, &readingv1.DeleteBookmarkRequest{BookId: bID, BookmarkId: bmID}); err != nil {
		return false, grpcx.FromStatus(err)
	}
	return true, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context, q *string, genre *string, format *model.BookFormat, authorID *string, year *int, page *int, limit *int) (*model.BookConnection, error) {
	pg := pagination(page, limit)
	req := &catalogv1.SearchBooksRequest{Page: int32(pg.Page), Limit: int32(pg.Limit)}
	if q != nil {
		req.Query = *q
	}
	if genre != nil {
		req.Genre = *genre
	}
	if format != nil {
		req.Format = strings.ToLower(string(*format))
	}
	if authorID != nil {
		id, err := parseID(*authorID, "author id")
		if err != nil {
			return nil, err
		}
		req.AuthorId = id
	}
	if year != nil {
		req.Year = int32(*year)
	}

	resp, err := r.Catalog.SearchBooks(ctx, req)
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	out := &model.BookConnection{Items: []*model.Book{}, PageInfo: pageInfo(pg, int(resp.GetTotalCount()))}
	for _, b := range resp.GetBooks() {
		out.Items = append(out.Items, bookFromProto(b))
	}
	return out, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	return r.getBook(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.UserProfile, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	p, err := r.User.GetMe(ctx, &userv1.GetMeRequest{})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	return &model.UserProfile{
		ID:             idString(p.GetId()),
		FirstName:      p.GetFirstName(),
		LastName:       p.GetLastName(),
		Email:          p.GetEmail(),
		Role:           p.GetRole(),
		PhoneNumber:    p.PhoneNumber,
		Bio:            p.Bio,
		TotalBooksRead: int(p.GetTotalBooksRead()),
		TotalPagesRead: int(p.GetTotalPagesRead()),
	}, nil
}

// MyLibrary is the resolver for the myLibrary field.
func (r *queryResolver) MyLibrary(ctx context.Context, status *model.LibraryStatus, page *int, limit *int) (*model.LibraryConnection, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	pg := pagination(page, limit)
	req := &userv1.ListLibraryRequest{Page: int32(pg.Page), Limit: int32(pg.Limit)}
	if status != nil {
		req.Status = strings.ToLower(string(*status))
	}
	resp, err := r.User.ListLibrary(ctx, req)
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}

	out := &model.LibraryConnection{Items: []*model.LibraryEntry{}, PageInfo: pageInfo(pg, int(resp.GetTotalCount()))}
	ids := make([]uint64, 0, len(resp.GetEntries()))
	for _, e := range resp.GetEntries() {
		out.Items = append(out.Items, libraryFromProto(e))
		ids = append(ids, e.GetBookId())
	}

	// One batch call for every entry's book, instead of one per entry.
	if len(ids) > 0 {
		books, err := r.Catalog.GetBooksByIds(ctx, &catalogv1.GetBooksByIdsRequest{BookIds: ids})
		if err != nil {
			// Degrade, don't fail: return the shelf with null books and one
			// SERVICE_UNAVAILABLE error, rather than one failed catalog call
			// per entry (or no shelf at all).
			graphql.AddError(ctx, ErrorPresenter(ctx, grpcx.FromStatus(err)))
			for _, item := range out.Items {
				item.Missing = true
			}
			return out, nil
		}
		byID := map[string]*model.Book{}
		for _, b := range books.GetBooks() {
			byID[idString(b.GetId())] = bookFromProto(b)
		}
		for _, item := range out.Items {
			item.Prefetched = byID[item.BookID]
			item.Missing = item.Prefetched == nil
		}
	}
	return out, nil
}

// MyHistory is the resolver for the myHistory field.
func (r *queryResolver) MyHistory(ctx context.Context, page *int, limit *int) (*model.HistoryConnection, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	pg := pagination(page, limit)
	resp, err := r.Reading.GetHistory(ctx, &readingv1.GetHistoryRequest{Page: int32(pg.Page), Limit: int32(pg.Limit)})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	out := &model.HistoryConnection{Items: []*model.ReadingHistoryEntry{}, PageInfo: pageInfo(pg, int(resp.GetTotalCount()))}
	for _, s := range resp.GetSessions() {
		out.Items = append(out.Items, historyFromProto(s))
	}
	return out, nil
}

// MyBorrows is the resolver for the myBorrows field.
func (r *queryResolver) MyBorrows(ctx context.Context, page *int, limit *int) (*model.BorrowConnection, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	pg := pagination(page, limit)
	resp, err := r.Borrow.ListMyBorrows(ctx, &borrowv1.ListMyBorrowsRequest{Page: int32(pg.Page), Limit: int32(pg.Limit)})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	out := &model.BorrowConnection{Items: []*model.BorrowRecord{}, PageInfo: pageInfo(pg, int(resp.GetTotalCount()))}
	for _, rec := range resp.GetRecords() {
		out.Items = append(out.Items, borrowFromProto(rec))
	}
	return out, nil
}

// MyBookmarks is the resolver for the myBookmarks field.
func (r *queryResolver) MyBookmarks(ctx context.Context, bookID string) ([]*model.Bookmark, error) {
	if err := requireUser(ctx); err != nil {
		return nil, err
	}
	id, err := parseID(bookID, "book id")
	if err != nil {
		return nil, err
	}
	resp, err := r.Reading.ListBookmarks(ctx, &readingv1.ListBookmarksRequest{BookId: id})
	if err != nil {
		return nil, grpcx.FromStatus(err)
	}
	out := []*model.Bookmark{}
	for _, b := range resp.GetBookmarks() {
		out = append(out, bookmarkFromProto(b))
	}
	return out, nil
}

// Book is the resolver for the book field.
func (r *readingHistoryEntryResolver) Book(ctx context.Context, obj *model.ReadingHistoryEntry) (*model.Book, error) {
	return r.getBook(ctx, obj.BookID)
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

// BorrowRecord returns BorrowRecordResolver implementation.
func (r *Resolver) BorrowRecord() BorrowRecordResolver { return &borrowRecordResolver{r} }

// LibraryEntry returns LibraryEntryResolver implementation.
func (r *Resolver) LibraryEntry() LibraryEntryResolver { return &libraryEntryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// ReadingHistoryEntry returns ReadingHistoryEntryResolver implementation.
func (r *Resolver) ReadingHistoryEntry() ReadingHistoryEntryResolver {
	return &readingHistoryEntryResolver{r}
}

type bookResolver struct{ *Resolver }
type borrowRecordResolver struct{ *Resolver }
type libraryEntryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type readingHistoryEntryResolver struct{ *Resolver }
