// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Author struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Biography *string `json:"biography,omitempty"`
}

type BookConnection struct {
	Items    []*Book   `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type Bookmark struct {
	ID        string  `json:"id"`
	BookID    string  `json:"bookId"`
	Page      int     `json:"page"`
	Note      *string `json:"note,omitempty"`
	Highlight *string `json:"highlight,omitempty"`
	Color     string  `json:"color"`
}

type BorrowConnection struct {
	Items    []*BorrowRecord `json:"items"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type HistoryConnection struct {
	Items    []*ReadingHistoryEntry `json:"items"`
	PageInfo *PageInfo              `json:"pageInfo"`
}

type LibraryConnection struct {
	Items    []*LibraryEntry `json:"items"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type Mutation struct {
}

type PageInfo struct {
	Page            int  `json:"page"`
	Limit           int  `json:"limit"`
	TotalPages      int  `json:"totalPages"`
	TotalCount      int  `json:"totalCount"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type Query struct {
}

type UserProfile struct {
	ID             string  `json:"id"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	Role           string  `json:"role"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	Bio            *string `json:"bio,omitempty"`
	TotalBooksRead int     `json:"totalBooksRead"`
	TotalPagesRead int     `json:"totalPagesRead"`
}

type BookFormat string

const (
	BookFormatDigital  BookFormat = "DIGITAL"
	BookFormatPhysical BookFormat = "PHYSICAL"
)

var AllBookFormat = []BookFormat{
	BookFormatDigital,
	BookFormatPhysical,
}

func (e BookFormat) IsValid() bool {
	switch e {
	case BookFormatDigital, BookFormatPhysical:
		return true
	}
	return false
}

func (e BookFormat) String() string {
	return string(e)
}

func (e *BookFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookFormat", str)
	}
	return nil
}

func (e BookFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BorrowStatus string

const (
	BorrowStatusActive   BorrowStatus = "ACTIVE"
	BorrowStatusOverdue  BorrowStatus = "OVERDUE"
	BorrowStatusReturned BorrowStatus = "RETURNED"
)

var AllBorrowStatus = []BorrowStatus{
	BorrowStatusActive,
	BorrowStatusOverdue,
	BorrowStatusReturned,
}

func (e BorrowStatus) IsValid() bool {
	switch e {
	case BorrowStatusActive, BorrowStatusOverdue, BorrowStatusReturned:
		return true
	}
	return false
}

func (e BorrowStatus) String() string {
	return string(e)
}

func (e *BorrowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BorrowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BorrowStatus", str)
	}
	return nil
}

func (e BorrowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BorrowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BorrowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LibraryStatus string

const (
	LibraryStatusWishlist  LibraryStatus = "WISHLIST"
	LibraryStatusToRead    LibraryStatus = "TO_READ"
	LibraryStatusReading   LibraryStatus = "READING"
	LibraryStatusCompleted LibraryStatus = "COMPLETED"
	LibraryStatusDropped   LibraryStatus = "DROPPED"
)

var AllLibraryStatus = []LibraryStatus{
	LibraryStatusWishlist,
	LibraryStatusToRead,
	LibraryStatusReading,
	LibraryStatusCompleted,
	LibraryStatusDropped,
}

func (e LibraryStatus) IsValid() bool {
	switch e {
	case LibraryStatusWishlist, LibraryStatusToRead, LibraryStatusReading, LibraryStatusCompleted, LibraryStatusDropped:
		return true
	}
	return false
}

func (e LibraryStatus) String() string {
	return string(e)
}

func (e *LibraryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LibraryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LibraryStatus", str)
	}
	return nil
}

func (e LibraryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LibraryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LibraryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
